### PR TITLE
AU-532 Add permission to bypass preview requirement, and code to enable Submit…

### PR DESCRIPTION
**Pull request by chris-hamper**
…button without preview

### CODE REVIEW

**Comment by janelletavares** [comment]
Is AU535 part of this branch?  Just trying to account for why it's currently filed as under code review.

**Comment by chris-hamper** [comment]
No, AU-535 isn't part of this.  I'm not sure what happened to the changes for AU-535.  I'll move the issue back to In Progress and get them in a new pull request.

**Comment by janelletavares** [comment]
I'll review this morning

**Comment by janelletavares** [comment]
With all features reverted and enabled, I still only see the preview button when I'm logged in as a content admin and I'm trying to submit a new article.

screen shot 2015-07-23 at 10 49 09 am

**Comment by chris-hamper** [comment]
The new permission hadn't been featurized in the Roles and Permissions feature.  It should work now.

**Comment by janelletavares** [comment]
Looks good

**Pull request merged**
