### PR TITLE
Enable commenting on posts and events

### PR DESCRIPTION
**Pull request by janelletavares**
[AU-677 Enable commenting on posts and events](https://backlog.acquia.com/browse/AU-677)

### CODE REVIEW

**Comment by chris-hamper** [comment]
Testing this...

**Comment by janelletavares** [comment]
I mentioned in IM that you should wait.

**Comment by janelletavares** [comment]
making a couple updates to this tonight...

**Comment by janelletavares** [comment]
Should be ready for review now

adding...
 [AU-732 email event admin about comments needing approval](https://backlog.acquia.com/browse/AU-732)
 [AU-730 email content admin about comments needing approval on new congrats](https://backlog.acquia.com/browse/AU-730)

**Comment by chris-hamper** [comment]
Testing this...

**Comment by chris-hamper** [comment]
Need to have the Congrats content type in master before this can be tested.  Seeing If I can test that PR first...

**Comment by chris-hamper** [comment]
- Attendees block appearing on Event Edit page
- Comments posted by users who can skip comment approval still send email
- Comment styling needs MUCH help

**Comment by chris-hamper** [comment]
Resolved feature conflicts and hid the Attendees block on edit form.  I'll create user stories for the other 2 points.

Should be ready to test.

**Comment by dannyacquia** [comment]
Looks good!  Merging now.

**Pull request merged**
