### PR TITLE
Au 682 add speaker

### PR DESCRIPTION
**Pull request by tedbow**
Changes event speaker from field collection to content type.

This allows others to add speakers without editing event  node.

Event speaker is moderated. New function_drz_custom_is_moderated_type determines if type is moderated. Add new types here in the future

There is link on the event type "Add new speaker" instead of form but could change to form in the future.

### CODE REVIEW

**Comment by chris-hamper** [comment]
Unfortunately, it looks like you and I changed the same code in parallel PRs (see #123).  I definitely like your approach with _drz_custom_is_moderated_type.

@tedbow I think the easiest way to resolve this is for me to tweak my changes in #123 to add the moderated type function, and for you to revert commit a64c13a.  Does that sound good?

**Comment by tedbow** [comment]
Sounds good reverted a64c13a.  pushed changes

**Comment by chris-hamper** [comment]
blocked on merge of #123 into master...

**Comment by chris-hamper** [comment]
Testing this...

**Comment by chris-hamper** [comment]
Problems I've found:
- 'Add new Event Speaker' link doesn't appear for non-admin users.  Manually browsing to /node/add doesn't list Event Speaker as a content type that can be created.  Permissions look OK for the Event Speaker content type, so something odd is happening.

Minor issues I've fixed and pushed up:
- Change Event Speakers view's caching settings to use Content-based caching
- Put speaker's name first, followed by description of presentation
- Add moderation help text to the Event Speaker content type's settings

**Comment by chris-hamper** [comment]
Hmm, seems like the creating of new speakers IS working.  Maybe I forgot to revert all the features?

It looks like notification emails are not being sent for new speaker content, though.  I'm looking into it...

**Comment by chris-hamper** [comment]
Added the missing rule trigger.  Should be set for a final test, @dannyacquia or @tedbow

**Comment by dannyacquia** [comment]
Everything seems to be working.  Email sent properly.

**Pull request merged**
