### PR TITLE
Make Drizzle features consistently named and add new hire fields to u…

### PR DESCRIPTION
**Pull request by janelletavares**
…ser profile

Added profile photo, job title, manager, office location, image url, previous experience, and drupal.org id.  Made previous experience and image url hidden from user profile view, as well as work state date and hybridauth identities.  

Allowing the user to update only profile photo and drupal.org id will come later.

### CODE REVIEW

**Comment by chris-hamper** [comment]
@janelletavares I'm curious about the reasoning behind adding another field for the user profile image, instead of using the built-in functionality.  Was there some issue that made it necessary?

I think that the user images on posts won't work if we don't use the built-in user image.

**Comment by janelletavares** [comment]
I just didn't see the build-in image field.  Let me look around some more.

**Comment by chris-hamper** [comment]
@janelletavares Lets get this pushed through minus the extra image field, as this issue is blocking a few other issues.

It also looks like the hiding of the HybridAuth table on the profile view isn't featurizable, so we'll need to do that manually on Stage, etc.

**Comment by janelletavares** [comment]
Sounds like a plan. I'll update the branch tonight.

-------- Original message --------

**Comment by janelletavares** [comment]
@chris-hamper Ready to go.

**Comment by chris-hamper** [comment]
OK, testing this one out

**Comment by chris-hamper** [comment]
Shouldn't we have all of the user fields hidden at /admin/config/people/accounts/display, except for drupal.org handle?  I thought that Bree wanted us to hide everything except in the particular views they were needed.

**Comment by janelletavares** [comment]
Authenticated users should only be able to edit their own drupal.org id and
their profile photo.  That's another user story.

But as far as what's displayed (what authenticated users can view of their
own profile and other's profiles), everything is displayed except image
url, previous experience, work date.  And I thought it made sense to hide
hybridauth's on top of that because it's not useful to any authenticate
user.

**Comment by chris-hamper** [comment]
Even manager and department? I thought those were supposed to be hidden on profiles.

**Comment by janelletavares** [comment]
I didn't put that in my notes.  I don't remember discussing those being
hidden.  Do you remember talking about that specifically with Bree?

**Comment by chris-hamper** [comment]
Maybe I was confused during the discussion about hidden vs. not editable.  Looking at the notes, that appears to be the case.

Things look good otherwise, so I'll merge.

**Comment by janelletavares** [comment]
Thanks!

**Pull request merged**
