### PR TITLE
AU-673 -665 -700 -686 -694 -695 -696 Use image styles, general styling cleanup

### PR DESCRIPTION
**Pull request by chris-hamper**
- Adds image styles to the photos in posts, and user photo thumbnails to drastically reduce download size an improve scrolling responsiveness.
- Limits Post teasers to one big photo, and 6 thumbnails
- Tweaks the node and user profile page styling a bit to improve readability and aesthetics.
- Changes the image style label for the style used for the profile page images to make it clear what it's used for
- Removed some unused theming code inherited from the parent theme, which could cause nasty surprises if left in

### CODE REVIEW

**Comment by chris-hamper** [comment]
hold off on reviewing this for a min.  Adding in AU-686, which is just a small tweak

**Comment by chris-hamper** [comment]
OK, good to go :)

**Comment by janelletavares** [comment]
I'll review

**Comment by janelletavares** [comment]
This is the post teaser I see now.  What is this supposed to look like?
screen shot 2015-09-04 at 7 39 34 pm

The blocks and post view definitely look better.

**Comment by janelletavares** [comment]
We should keep the 100x100 profile photo on the post view, rather than a 50x50.  That's something we've discussed with Bree, and I don't think there's been any interest in changing it.

**Comment by janelletavares** [comment]
Does this pull request cover AU-699, too?

**Comment by janelletavares** [comment]
Just FYI, I'm waiting to work on my styling updates until this branch is merged.

**Comment by chris-hamper** [comment]
Hmmm, not sure why that teaser is showing up weird for you.  Thumbnails were showing up below the larger photo on my local env, and on Cloud Dev.

I hadn't realized that the full Post showed a different size of user image.  I might be able to change that back to 100x100. User photos are a real pain to make different sizes; I had to jump through all kinds of hoops just to get 2 sizes. Now that I have an idea how, I can probably fix it more easily.

This only would partially cover AU-699, as I didn't work with Events theming.

**Comment by janelletavares** [comment]
I'll break up AU-699 into sub-tasks.

**Comment by janelletavares** [comment]
I'm going to test again... maybe it'll be fine now.

**Comment by janelletavares** [comment]
Test after fixing up settings and db in local environment.  Works.

**Pull request merged**
