### PR TITLE
AU-514 -535 user profile cleanup, give user admins access to hidden fields

### PR DESCRIPTION
**Pull request by chris-hamper**

### CODE REVIEW

**Comment by janelletavares** [comment]
I'll review this morning

**Comment by janelletavares** [comment]
The member history is splitting birthday month and day in manage display... that's not right.  Is there a way to display birthday month and day as just Birthday: <Month> <Day>

**Comment by janelletavares** [comment]
Were you going to hide the hybridauth tab from the user profile edit display?

**Comment by chris-hamper** [comment]
We could combine the Birthday month and day in theming.  Keeping the HybridAuth tab for now as we had discussed at the Scrum

**Comment by janelletavares** [comment]
Ok.  Let's talk about hybridauth in scrum again tomorrow.  What about member history splitting birthday month and day?

**Comment by chris-hamper** [comment]
That's a result of the values being in two different fields; a requisite for my implementation of the Birthdays block.  We can create a theme override to combine them into one line if that's important.  But if Bree wants us to hide them anyway, it's probably not worth the effort.

**Comment by janelletavares** [comment]
I don't think we're understanding each other.  Here's how it looks after I pull in your branch...
screen shot 2015-07-24 at 9 17 40 am
screen shot 2015-07-24 at 9 17 17 am

and I the logical thing would be to group month and day like...
screen shot 2015-07-24 at 9 19 54 am
screen shot 2015-07-24 at 9 19 28 am

**Comment by chris-hamper** [comment]
History should be hidden, maybe it's not featurizable?  May need to set it manually on Stage.

**Comment by janelletavares** [comment]
In one of our meetings, Bree said she thought it was fine to show history.
I don't think it's necessary or as relevant as showing work start date.
I've not tried to hide the history field previously.

**Comment by chris-hamper** [comment]
I don't see any purpose for keeping the history in; if I'm not mistaken all it gives us is the date the account was created.  Confirmed that it's not featurizing.

**Comment by janelletavares** [comment]
Which would be the same date for most Acquians, right?  Yeah, that's not
providing anything useful so I'm fine with hiding it.

**Comment by janelletavares** [comment]
To follow up, I should ignore the location of history when I pull in your branch because it's being hidden was not featurized?  If that's the case, let me know and then I'll be ready to accept and merge this.

**Pull request merged**
