### PR TITLE
AU-510 Disabled comments for Articles

### PR DESCRIPTION
**Pull request by Cameronbochman**
I changed the content type Articles to have a closed comment section. This change only works for new articles posted. To test: create a new article and check if the comment section is closed or not.

### CODE REVIEW

**Comment by janelletavares** [comment]
@Cameronbochman Did you consider disabling the comment module?

**Comment by janelletavares** [comment]
My concern is that this method is prone to breaking.  As of now, authenticated users can only create Articles.  But if we need another content type in the future, comments will automatically be enabled and then we will have a regression.

**Comment by ndelrossi** [comment]
I was working with Cam on this story. I think you make a great point @janelletavares. It seemed like Bree didn't want commenting at all. Maybe we should change the story to something like: "As a site administrator, I want commenting disabled on the website so that strange conversations don't happen anywhere on Drizzle"

**Comment by janelletavares** [comment]
Sure, that sounds like a reasonable update.

**Comment by ndelrossi** [comment]
I am closing this PR and not merging. We decided it would be better and easier to disable the comment module on staging. I have disabled the module and tested to see that you can no longer add a comment to any content type.

**Pull request closed without merging**
