### PR TITLE
Au 519 user posts on profile

### PR DESCRIPTION
**Pull request by dannyacquia**
https://backlog.acquia.com/browse/AU-519

Changed permissions for authenticated users to view other user's profiles.
Added context filter for blocks on user profiles
created a view block that only displays on a user's profile page that shows their last 10 published posts
created a new feature called "Drizzle Views Features"

Enable the new feature and revert the others to see the changes.

TODO: Discuss which fields we want to show, how many posts to display, where to place the block.

### CODE REVIEW

**Comment by allygonthier** [comment]
testing this...

**Comment by allygonthier** [comment]
when I masqu'd as an authenticated user and then browsed another user's profile, a section for HybridAuth identities displayed, not sure we want this information displayed this way?

Otherwise, works as expected.

**Comment by dannyacquia** [comment]
Ally, that sounds like another story we might want to make to further modify what a user sees on a profile.  For now I'll mark this particular story as in testing and merge it in to master.

**Comment by chris-hamper** [comment]
I'll add some code to my user profile cleanup in drz_custom to hide the display of that on the user profile view tab.  No need to clutter up the user view.

**Pull request merged**
