### PR TITLE
AU-515 Mobile UX, New Hires page styling

### PR DESCRIPTION
**Pull request by chris-hamper**
Also includes AU-740 and -748

### CODE REVIEW

**Comment by chris-hamper** [comment]
Hold off on testing this for a min... missed something

**Comment by janelletavares** [comment]
I thought the plan was to hide the sidebar blocks on mobile?

**Comment by chris-hamper** [comment]
OK, should be ready to go, now.  Only showing the Congrats block.

**Comment by dannyacquia** [comment]
Testing this now.

**Comment by dannyacquia** [comment]
This seriously looks and responds so amazingly well!  Great job Chris.  This will make a huge difference for maintaining active visitors!

**Pull request merged**
