### PR TITLE
Allow users to click on photos and see full resolution using colorbox

### PR DESCRIPTION
**Pull request by kdonaldson**
I'm ready
https://backlog.acquia.com/browse/AU-659

### CODE REVIEW

**Comment by chris-hamper** [comment]
@kdonaldson this doesn't quite seem to be working.  I have a feeling something didn't get featurized.  Could we meet for a few and figure out what is missing?

**Comment by janelletavares** [comment]
I meant to look into it, but I wasn't sure there was a way to featurize the
image file type setting to use colorbox by default. Might need some custom
code?

**Comment by chris-hamper** [comment]
I can't seem to find the setting to change in order to use Colorbox for the images.  Do you remember the configuration path for it?

**Comment by janelletavares** [comment]
First checkbox under Enable Displays

screen shot 2015-09-04 at 9 32 01 am

**Comment by janelletavares** [comment]
Works great for me after checking colorbox for default and teaser, except the issue Keith noted when we were talking earlier about the first small photo not being click-able.  I'm looking into it, and it appears to be a relic from either bootstrap or ember, placing the element-invisible class where we didn't intend it to be.

**Comment by janelletavares** [comment]
Ember isn't enabled, so it must be bootstrap...

**Comment by janelletavares** [comment]
Nope... that's not it.

**Comment by chris-hamper** [comment]
The CSS used to style the thumbnails has side-effects like that.  I cleaned CSS up a bit for AU-673 (see pull request), which should fix that clickability problem

**Comment by janelletavares** [comment]
I merged both branches into a local branch, and the colorbox behavior now works on all images in the teaser and full node view.  But, none of the images are thumbnail size in the teaser... is that a database problem due to renaming image styles?

**Comment by janelletavares** [comment]
Did a fetch and turned off colorbox for the node teaser.  same problem.

**Comment by chris-hamper** [comment]
After extensive fiddling, it appears the colorbox display mode isn't properly grouping images into a gallery, thus it doesn't respect the first image vs. other images image styles on the "Manage file display".  As a result, all images load as the same size on the front page and inside post pages.  And on top of that, I can't get my branch's code (which explicitly sets image styles in theming) to override this behavior, either.

I really like the lighbox effect this module provides, but it doesn't support smaller thumbnail files or limiting the number of thumbnails, and thus increases the download size of the post teasers, sometimes by an order of magnitude or more for posts with multiple images.

What do you think about testing and merging only pull #105 for now.  It provides equivalent functionality, just doesn't look quite as nice.  It also adds a lot of other image-styles related improvements, and styling fixes on top of that.

I can continue to look into incorporating the Colorbox, or a similar lightbox effect on top of #105

**Comment by janelletavares** [comment]
That sounds like a good plan, Chris.  I'll review 105 as a standalone today
now that I know you've looked into this.

**Comment by chris-hamper** [comment]
Going to close this PR out and open a new one once a more limited use of colorbox/lightbox is implemented.  Thanks for all your effort on this @kdonaldson  I'm sorry it didn't work out.

**Pull request closed without merging**
