### PR TITLE
AU-494. Image Captions

### PR DESCRIPTION
**Pull request by ndelrossi**
Users are now given the option of adding a caption to an article image. Installed module Image Field Caption. Edited article image settings and added to drz_features.

To test, create an article and upload and image. There will now be a text area to enter a caption. If you submit the new article the caption will display underneath the image.

### CODE REVIEW

**Comment by janelletavares** [comment]
@ndelrossi Review in progress...

**Comment by janelletavares** [comment]
@ndelrossi I had to manually enable the image field caption module to get it to work, after the files dir shenanigans.  Sometimes, the dependency on a module must be explicitly written into the .info file of a module, which I believe is the case here after talking to Ted.  Please do that and update the branch.  Looks like...
--- drz_articles.info	2015-07-02 09:26:03.000000000 -0400
+++ drz_articles.info.update	2015-07-02 12:32:24.000000000 -0400
@@ -8,6 +8,7 @@
 dependencies[] = strongarm
 dependencies[] = taxonomy
 dependencies[] = text
+dependencies[] = image_field_caption
 features[ctools][] = strongarm:strongarm:1

**Comment by ndelrossi** [comment]
Thanks @janelletavares. I have added another commit with the dependency added to the .info file. Hopefully working now.

**Comment by janelletavares** [comment]
@ndelrossi Looking solid now, thanks.

**Pull request merged**
