### PR TITLE
Update event views; display article event entity reference as link; a…

### PR DESCRIPTION
**Pull request by janelletavares**
…llow everyone to access attendees flag

Noticed a couple other things while I was making these changes, so I'll list them all here.
1) manage display of Article so that event entity reference is a link with an inline label
2) allow all users to access the attendance flag (previously none had access)
3) add username and user picture to both attendees and posts about an event views
4) sort attendees by who most recently flagged yes for attendance and display as grid

### CODE REVIEW

**Comment by janelletavares** [comment]
Overboard to allow all roles to access flags?  Should it just be authenticated users?

**Comment by janelletavares** [comment]
@allygonthier @chris-hamper @dannyacquia This pull request has been sitting for a week.  Would someone please review?

**Comment by dannyacquia** [comment]
Looks good to me!

**Comment by janelletavares** [comment]
Thank you

**Pull request merged**
