### PR TITLE
AU-745 flag hover text, re-enable un-like

### PR DESCRIPTION
**Pull request by chris-hamper**

### CODE REVIEW

**Comment by chris-hamper** [comment]
@janelletavares please test this one if you have time.  I'd like to get your feedback on the flag button design choices and wording

**Comment by janelletavares** [comment]
I should be able to check it out tonight.

**Comment by janelletavares** [comment]
I have network issues at home... looking this morning.

**Comment by janelletavares** [comment]
It might be a bit more user-friendly, but it needs some work.  Initially, I thought the hover text would be one of those little grey boxes with help/description that appears above the cursor when you hover over something with the cursor. My inclination now is to have the like button always say "Likes (#)" whether or not the user has liked the post, and then the hover text would indicate if the available action is "Like it!" or "Unlike it". (no hyphen) For attendance, I think the sad face is unnecessary.

The two different shades of blue aren't working for me.  Is it easy to make all blues on this site Acquia blue - links, text, boxes, buttons, etc?
screen shot 2015-09-24 at 10 30 36 am

I asked someone around my desk about the user experience of these buttons, and he recommended that I consult a UX developer in my office neighborhood. I'll do that later and get back to you on the feedback.  For what it's worth, he's rather have a thumbs up or down rather than a button and the like tally be outside the button.

**Comment by chris-hamper** [comment]
Updated the button coloring based on your feedback.  Also tweaked working based on feedback from Bree.

It would be nice to move the count outside the button, but that won't be a quick change, and I've already spend more time on this than I had intended.

**Comment by chris-hamper** [comment]
Thanks for your testing and feedback @janelletavares  I went with using "Likes" as the text when not yet liked, to make it clear the number is the Likes count.

I'm going to test one more time on Dev and merge, so it's ready for a demo/training Bree will be doing tomorrow for prospective Event Admins.

**Pull request merged**
