### PR TITLE
AU-547 Style sticky posts with a thicker border; remove 'promoted to …

### PR DESCRIPTION
**Pull request by janelletavares**
…front page' filter from the front page view; recreate image style usage

### CODE REVIEW

**Comment by janelletavares** [comment]
Working on merge conflicts locally...

**Comment by janelletavares** [comment]
Resolved.  Ready to review.  I showed Bree a screenshot of the thick border for sticky posts, and she liked it.

**Comment by janelletavares** [comment]
My local db doesn't have the image styles, for some reason.  Ignore the comment about image styles.

**Comment by janelletavares** [comment]
Fixed merge conflicts.  Ready for review.

**Comment by allygonthier** [comment]
confirmed sticky posts have thicker border

**Pull request merged**
