### PR TITLE
AU-500 Randomizes new hires, enables caching of new hire views, adds depende…

### PR DESCRIPTION
**Pull request by chris-hamper**
…ncy on date_views module

### CODE REVIEW

**Comment by janelletavares** [comment]
I see that the posts are not affected by changing pages of new hires, which is great.  Thanks for fixing that.

The randomization is not what I had in mind.  I just see the first four new hires alphabetically on the first page of new hires.  When I refresh the page, I see the same new hires.  Maybe those were unreasonable expectations, and rotating on a specific time interval is fine.  Though, I would like to see something closer to 5 minutes on the block so that if someone only spends only a few minutes on Drizzle a day, the new hires would look dynamic and updating.  When I go to the next page of new hires, I see some of the same new hires as on the front page.  That's for sure a problem.  Could you explain the time interval on the caching of the page view to me?

Instead of having an "All New Hires" link, I was thinking clicking on any teaser would take you to that new-hires page through the Link Display: Custom Link setting, and then those photos would link to user profiles like they already do.  Bree and I refined some of these things during our meeting that we can discuss in scrum tomorrow.

**Comment by chris-hamper** [comment]
I only randomized the front page block view.  Seemed unnecessary for the full page view

**Comment by janelletavares** [comment]
Yes, that makes perfect sense about the full page view.  But the
randomization of the block view is not behaving properly with pagination.

**Comment by janelletavares** [comment]
@chris-hamper @allygonthier @dannyacquia 

Please correct me if I'm wrong, but this is a summary of what we concluded about this branch/feature during Friday's meeting:
1) remove pagination
2) randomize front page order more frequently (like 1 minute)
3) show all new hire fields for all new hires on the archive view
4) order new hires on archive from most recent to least recent for the past 4 weeks
5) make the thumbnail of new hires styled as a circle
6) show the total number of new hires somewhere in the front page block
7) clicking a new hire from the front page takes you to the new hire archive view or have an archive link
8) clicking a new hire from the archive view takes you to the user profile

Having the current plan of record and all notes in one location is still in progress.  Hope to be done by this afternoon's meeting.

**Comment by chris-hamper** [comment]
@janelletavares I've implemented all the proposed changes listed above, except for #5 (this is theming-related), and #6 (couldn't figure out a way of doing it with views).  The original plan to implement #6 was broken by removing the pagination on the front page block (it never gives greater than 4 new hires).  I could imaging doing it in a custom module...

What are your thoughts?

**Comment by dannyacquia** [comment]
Hey Chris.  I just tested this out as well and when pagination is enabled, I get a full count, but when it is disabled it just gives 4 as the @total.

I spoke with Janelle and suggested we keep pagination on, but use CSS to hide the pager buttons.  Neither of us can think of a reason not to do this as it won't impact the site or make anything end up hinky.

The css would be as follows:

#block-views-new-hires-block .pager {
  display:none;
}

What are your thoughts?

**Comment by chris-hamper** [comment]
Good idea, hadn't thought of that.  I'll implement it.

**Comment by chris-hamper** [comment]
@janelletavares I implemented @dannyacquia 's suggestion of hiding the pager.  It's looking pretty good now :)

Should be ready to test.

**Comment by janelletavares** [comment]
I'll test it tonight.  Thanks all.

**Comment by janelletavares** [comment]
Looks great.  The new hire fields could use some theming help, but that's another user story for another sprint.  Thanks for the iterations!

**Pull request merged**
