### PR TITLE
added links to footer

### PR DESCRIPTION
**Pull request by allygonthier**
in this branch I was planning on doing both my footer events but settled on completing https://backlog.acquia.com/browse/AU-561 first.
I added a menu to the footer and re-created the menu feature which I hope grabbed this information.
I also added some styling to the footer in CSS and I hope you all like it!

### CODE REVIEW

**Comment by allygonthier** [comment]
this won't work right now, danny showed me why so we need to wait for my other pull request

**Comment by allygonthier** [comment]
ok this branch should now be up-to-date!  please review

**Comment by janelletavares** [comment]
Reviewing...

**Comment by janelletavares** [comment]
Nits about the links list... I'd prefer Acquia University to Acquia U, and also Referrals to Add New Referrals.

Please update the display name for the featured event block view from 'Block' to 'Featured Event'.

**Comment by allygonthier** [comment]
updated feature for menu and view with these changes, please review..

**Comment by janelletavares** [comment]
It looks like far too much was deleted in your last commit.  Unintentional features snafu?  I see the block name updated, but the link texts are the same.

**Comment by janelletavares** [comment]
Bree mentioned recently moving referrals from the footer links to a Jobs drop down menu in the main menu.  There would link internal job reqs, referrals, maybe a couple other things.  As of now...

**Comment by janelletavares** [comment]
Scratch that last comment... go with the list you have.

**Comment by allygonthier** [comment]
I'm not sure how to get these changes, my only suggestion is to push these and then maybe consider making those menu changes on production?

**Comment by janelletavares** [comment]
Let me take a look tonight...

**Comment by janelletavares** [comment]
I see the menu feature as rebuilding now.  I'll merge and we'll sort this out on stage and/or production.

**Pull request merged**
