### PR TITLE
AU-706 update Drupal core and contrib modules to latest

### PR DESCRIPTION
**Pull request by chris-hamper**
Fixes security vulnerabilities in Core and ctools

### CODE REVIEW

**Comment by janelletavares** [comment]
Not immediately sure how to fix this error that occurs when I pull over the changes.

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /Users/janelle.tavares/Sites/devdesktop/pull/acquiau-drizzle/docroot/profiles/acquia/modules/sqlsrv/sqlsrv.install on line 127

**Comment by chris-hamper** [comment]
@janelletavares  When and where do you see that error message?

**Comment by janelletavares** [comment]
@chris-hamper I did a checkout of your branch and then ran drush-refresh.sh.  At that point, I got a couple dozen of these parse errors.  Nothing else seems to be wrong, though.

**Comment by chris-hamper** [comment]
Sometimes I need to pull down a fresh copy of the DB from Dev, or occasionally Prod, to fix error messages like that.  Just needed to do that same thing for the PR I'm testing now.

**Comment by janelletavares** [comment]
I just pulled from prod yesterday or the day before.

**Comment by chris-hamper** [comment]
I don't see any errors on my local, or on Cloud Dev, so it must be an issue with your local env.

**Comment by chris-hamper** [comment]
I did some manual testing on Dev, and didn't see anything broken.  Would you like to test further there, or is going ahead with the merge OK?

**Comment by janelletavares** [comment]
I'll take one more look after lunch

**Comment by janelletavares** [comment]
It happens every time I run drush cc all.  Perhaps it's just an annoyance.  I don't see anything in the logs.  Merging...

**Pull request merged**
