### PR TITLE
event admin and a couple views updates

### PR DESCRIPTION
**Pull request by janelletavares**
Links to user stories:
[AU-668 create event admin role](https://backlog.acquia.com/browse/AU-668)
 - create event admin role with permissions to create, edit, delete all events

[AU-683 allow event admins to email attendees](https://backlog.acquia.com/browse/AU-683)
 - have existing attendees block show for all non-event admins
 - new view for event admins with user bulk operations that allows for emailing attendees

[AU-697 Update users posts title](https://backlog.acquia.com/browse/AU-697)
 - add apostrophe in local view name
 - put user's name in the header of the view (may need some styling in another pull request)

[AU-702 cache new hire shoutout for only one minute](https://backlog.acquia.com/browse/AU-702)
 - change from never caching to caching every minute

### CODE REVIEW

**Comment by chris-hamper** [comment]
Testing this now...

**Comment by chris-hamper** [comment]
Here's what I have to report so far:
- There's no way for an Event admin to see unpublished events, or publish unpublished events.  May not be a big deal, since Events are published by default.  There's no easy way to give this role permissions to do those specific things.  Can add a couple of Contrib modules if absolutely needed.
- New Event page looks very funky on the non-admin theme.  I'd recommend adding permission to view the admin theme
- Should pre-fill the email Recipient field and hide it
- Sending of emails fails due to insufficient permissions

Everything else looks good.

**Comment by janelletavares** [comment]
I don't think we need to worry about unpublished events.

There's a user story for pre-filling the recipient field and hiding it.
I've got a few form alter tasks to do, so I would going to wrap them into
one pull request.

Where do I set permission to use the admin view on new event form?

Thanks for the review.

**Comment by chris-hamper** [comment]
We'll need to add a dependency to the actions_permissions module to one of our features to enable it, and give Event Admin role permission to 'Execute Send e-mail'.

Finally, featurize all the new 'Execute' permissions in the Drizzle Roles and Permission feature

**Comment by chris-hamper** [comment]
This should be ready for a quick test and merge

**Comment by janelletavares** [comment]
Noted... will get to it today.

**Comment by janelletavares** [comment]
I've added a few more check boxes under VBO.   Merge at will if you're comfortable with the changes.

**Comment by chris-hamper** [comment]
The bulk email still has some issues.  I'm going to merge this to get the Event Admin role and permissions into master, and create a couple user stories for the issues I've found:

- Bulk email to event attendees only emails to some/one attendees
- Very poor UX for bulk send operation

**Pull request merged**
