### PR TITLE
AU-580 Callout number of Acquians on the front page

### PR DESCRIPTION
**Pull request by janelletavares**

### CODE REVIEW

**Comment by allygonthier** [comment]
reviewing..

**Comment by allygonthier** [comment]
something is up with this view and needs someone else to take a look.

**Comment by janelletavares** [comment]
Current analysis...
"there’s a checkbox that says something like “show header even if view is empty” but it doesn’t seem to be respected"

**Comment by janelletavares** [comment]
The very talented Richard Burford has rewritten the block in custom code.  Works like a charm now.  @allygonthier @dannyacquia ready to be retested.

**Comment by allygonthier** [comment]
@janelletavares , do you still want me to test this and merge it or wait to it has to be moved to the footer?

**Comment by janelletavares** [comment]
Please wait until I move it to the footer, thanks.

**Comment by janelletavares** [comment]
Merged and make updates per requests in the afternoon meeting yesterday.
1) move number of employees to footer
2) link to new hire archive
3) hide new hire shoutout on front page when there are no results

@allygonthier ready for review!

**Comment by janelletavares** [comment]
Group review complete

**Pull request merged**
