### PR TITLE
Au 520 infinite scroll front page

### PR DESCRIPTION
**Pull request by dannyacquia**
https://backlog.acquia.com/browse/AU-520

Added Views Infinite Scroll module.
Edited css file in acquia-drizzle theme to display: none pagination links at the bottom of the front page
created a new view for the front page
Updated Drizzle Views Feature

Once you have the features reverted, you should see only two posts on the front page.  Then when you scroll down, two more will load.  This will continue happening until all content is visible.

TODO: Decide what a good number is for number of items to load each time you scroll down.

This pull request is dependent on AU-519.  Please review that one first.

### CODE REVIEW

**Comment by janelletavares** [comment]
Will review tonight, unless you have changes you want to make.

**Comment by janelletavares** [comment]
Generally looks good.  It seemed from the discussion today that 10 posts to start and 10 new posts every time the user scrolls to the bottom was the popular vote.

It would be convenient to include the views_ui module as a dependency in the views feature so that it's always enabled by default while we are developing.  If it's good practice, it can be removed from dependencies at a later point when it's not routinely needed.

**Comment by chris-hamper** [comment]
I'd recommend against adding Views UI as a feature dependency - it will
make it difficult to turn off later.  We really shouldn't be using Views UI
on Stage anyway.

-- 

Chris Hamper* | *
*Acquia University** |*

* Acquia
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>
*

*M:* 413-464-4280
*E: *chris.hamper@acquia.com <chris.hamper@acquia.com> | Skype: hampercm
W: http://www.acquia.com
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>

53 State St., 10th Floor, Boston, MA 02109

**Comment by janelletavares** [comment]
Ok

**Pull request merged**
