### PR TITLE
Congrats content type and block; be able to like congrats and events

### PR DESCRIPTION
**Pull request by janelletavares**
[AU-707 Congratulations](https://backlog.acquia.com/browse/AU-707)
allow anyone to submit a congrats
moderate it
show last 5 published on front page block
link to full congrats content and user profile in front page block

[AU-729 also like events and congrats](https://backlog.acquia.com/browse/AU-729)
add the links in the bottom right corner, as usual

[AU-730 email content admin upon submitting new congrats](https://backlog.acquia.com/browse/AU-730)

### CODE REVIEW

**Comment by chris-hamper** [comment]
Testing this...

**Comment by chris-hamper** [comment]
- "Type of Accomplishment" is restrictive.  Is it really important?  Can we make this something more flexible?
- Congrats block should be hidden if no active Congrats found.  This might not be a big issue, if there will always be Congrats active
- Why have Title field hard-coded, and then have a Summary sentence that effectively is the Title?
- Get rid of preview option completely?
- Styling in Congrats block needs improvement: user name and title right next to each other on same line.
- More than one user for a Congrats?  As with the build week congrats, more than one person may be involved

Otherwise looks good!

**Comment by janelletavares** [comment]
1) It's meant to be restrictive.  The congrats block should have very
specific job-related content.  Everything else goes in a Post.
2) Why would the congrats block be different from the other sidebar
blocks?  They all have 'none found' no results behavior.
3) The summary sentence is not effectively the title.  The title is always
'Congratulations', and the summary sentence would be something like
'transitioned to full time in the business engineering group'.  I played
around with having the summary sentence be the default title field, and I
really didn't like it.  Does that clarify anything?
4) yes, there should be no preview.  let me go back and check that.
5) user name and summary sentence should be right next to each other, so it
reads like a sentence.  What else did you have in mind?
6) Only individual accomplishments in the Congratulations block.
Everything else, like group projects, goes in a Post.  The build week
congrats was a hacked up example.

Thanks.

**Comment by chris-hamper** [comment]
3) I would suggest using theming in the future to put a "Congratulations" heading at the top, and restyling the title field to look the way you want.  Having the title hard-coded comes with some difficulties: can't tell which congrats is which on the "all content" view, for example
5) Perhaps a separating hyphen or colon.  Really looks funky to me the way it is now

**Comment by janelletavares** [comment]
3) Would it help in the content admin view to do a programmatically
concatenated title that's congratulations+username or something like that?
 and then just hardcode the title to Congratulations somewhere else?
5) My reaction is that a hyphen or colon between the subject and predicate
of a sentence would look very wrong.

**Comment by janelletavares** [comment]
Are we looking at the same thing?
screen shot 2015-09-14 at 11 18 17 am

**Comment by chris-hamper** [comment]
I see what you were going for now.  The issue is you're assuming people will always enter content in the two separate fields in a specific way that will flow together nicely.  This will not be the case if users are able to submit congrats.  And, even moderators might not get it right 100% of the time.  I like the idea, but think it will be not-so-great in practice.

With moderation, it might be an acceptable strategy, but there should probably be help text, or more ambitiously we can style the form so that the user and summary are beside each other.

**Comment by janelletavares** [comment]
changed summary sentence to summary predicate, in case that would be confusing.

**Comment by chris-hamper** [comment]
I think calling it "summary predicate" is even more confusing. Most people aren't very familiar with grammar terms such as that

**Comment by janelletavares** [comment]
There is already help text with an example for the summary field.  Putting the fields right next to each other might help.  I'm sure the content admins will not have a problem editing the congrats to be coherent in the block, if need be.  People will get the hang of it after they read content in the congrats block for a while.

**Comment by janelletavares** [comment]
I don't think you give people enough credit!  What else do you suggest?  just "summary", or "the rest of the summary sentence"?

**Comment by dannyacquia** [comment]
That last commit looked a little wonky with deleting the comment body from the feature.  Will disable comments with drupal best practices later on.

Also moved drz_congrats from sites/all/modules to the proper sites/all/modules/features.

Also while testing, I had no idea what the term "Predicate" meant.  We may want to get with Bree and choose a better wording for that field.  Something like "Summary of accomplishment".  Then in the help text explain that the name of the Acquian will precede the SoA.

**Comment by janelletavares** [comment]
Bree and I had faith that people would remember the word predicate. C'est
la vie...

**Comment by dannyacquia** [comment]
I had to look it up, and even after reading the definition, I didn't necessarily understand what the field was asking for...especially since there was no field labeled "Summary subject"....It's confusing and you can't assume people will understand that the field Acquian is the summary subject.  I think it is best to use basic vocabulary so that all levels of english education can understand it.  For instance, our international coworkers might never have been taught the term 'predicate'.

**Comment by janelletavares** [comment]
That's funny... most of my international friends learned English far more
vigorously than most of the Americans I know.  In any case, we can
certainly update the field names.  I think once people see a few congrats
in the block, they'll get the hang of it regardless of the field names.

**Comment by dannyacquia** [comment]
Spoke with Bree to get the exact wording and help text she wanted.  This should be good to merge now, which will unblock the pull request for comments.

**Comment by janelletavares** [comment]
I'm going offline now... Gotta get to the airport.

**Pull request merged**
