### PR TITLE
Added to allowed tags in 'filtered html' to match wysiwyg profile.

### PR DESCRIPTION
**Pull request by tedbow**
Added to allowed tags in 'filtered html' to match wysiwyg profile. Removed extra buttons on wysiwyg profile.

Regular users can now not upload images into the body via wysiwyg.

https://backlog.acquia.com/browse/AU-710

### CODE REVIEW

**Comment by chris-hamper** [comment]
Testing this...

**Comment by chris-hamper** [comment]
A few issues I've noticed:
- No WYSIWYG profile for Full HTML
- Still wiping out line breaks and paragraph breaks
- No ability to use subscript, superscript, or code tags (sees like it will limit the range of possible geek-humor)  ;)

Looks like it needs more work.

**Comment by chris-hamper** [comment]
Added a commit to fix line and paragraph breaks being removed, and other points I had mentioned above

**Comment by janelletavares** [comment]
I'll take a look, too.

**Comment by dannyacquia** [comment]
Just checked this out.  Works great.  Also checked full html to make sure I could switch to source code and type in straight html and it worked like a charm.

Ready to merge.

**Pull request merged**
