### PR TITLE
added pulish date module and featurzied front page view to sort by pu…

### PR DESCRIPTION
**Pull request by allygonthier**
…blished date

added published date module and updated front page view to sort posts by published date and then recreated view feature

### CODE REVIEW

**Comment by janelletavares** [comment]
I'll review in the morning

**Comment by janelletavares** [comment]
1) Add publish date module explicitly as a dependency for the views feature.
2) Maybe this is because of the missing module dependency, but I see the sort criteria as "published", which means whether or not the post is published or unpublished.  That doesn't help us.  You need to specify that the sort criteria as "Post date" and pick descending and second granularity.

**Comment by allygonthier** [comment]
ok, this module is terrible so I found a better one, made sure that it the dependency was featurized and also update the view according.  @janelletavares, thanks for your patience

**Comment by janelletavares** [comment]
Looks great.  Hopefully that new published date field will be accessible when we are updating the Post teaser and full rendered view to show published date and not submitted date.  Thanks!

**Pull request merged**
