### PR TITLE
AU-571 -581 Don't allow anonymous users to see public media; Create user impo…

### PR DESCRIPTION
**Pull request by janelletavares**
…rt role which is authenticated user plus user import permissions; Update user admin role to be able to assign user admin role to others as well as all roles

@chris-hamper @allygonthier @dannyacquia Was there any reason that the user admin role could not previously set other users to also be user admins?

### CODE REVIEW

**Comment by chris-hamper** [comment]
What is meant by "Don't allow authenticated users to see public media"?  Did you mean "anonymous users" instead?

I'd recommend removing the permissions you just added to the "user import" role from the "user admin" role. Drupal best practices generally say to not "overlap" user roles' permissions.  Instead make each role as specific as possible, and give users multiple roles as needed.  Not sure if that made sense, but ping me if clarification is needed.

**Comment by janelletavares** [comment]
I did mean anonymous users!  Sorry for the confusion.  Let me update that.

That makes sense about removing permissions from the user admin role.  I
will add another commit to this branch.

Thanks for the review.

**Comment by chris-hamper** [comment]
@janelletavares I'm not seeing the "user import" role.  Did you forget to add it to the feature?

**Comment by janelletavares** [comment]
You are correct... I did not featurize it properly.  Should be good to go
now.

**Comment by chris-hamper** [comment]
It looks like authenticated users need a few more permissions, otherwise they can't access the full-sized view of media:
- download any image files
- download any video files
- view own files
- view own private files

With these permissions, users can see images in the media browser that they've already uploaded, and can attach them to another post, but can't change the caption on them.  Users can browse others' files.  Seems like OK behavior to me.

**Comment by chris-hamper** [comment]
I can commit the new permissions I listed if that sounds OK

**Comment by janelletavares** [comment]
What's the use case for attaching a photo or video to more than one post?
I'm not sure that's keeping to the intention of simplifying the interface.

I don't want users to browse others' files, but they should be able to view
those files in a post.

**Comment by janelletavares** [comment]
I see the problem... cannot click on an image and see its own file page - get access denied instead.  Will update those permissions and commit it to this branch.

**Comment by janelletavares** [comment]
Chris is taking care of fixing up this branch and then merging.  Thanks, Chris!

**Pull request merged**
