### PR TITLE
Au 546 frontpage album cover and thumbnails

### PR DESCRIPTION
**Pull request by dannyacquia**
https://backlog.acquia.com/browse/AU-546

After pulling this you'll need to do a drush fra to get the articles feature reverted.  All the other changes are css and template related, so just clear cache and everything should be visible.

### CODE REVIEW

**Comment by allygonthier** [comment]
so this works as expected with the media files and thumbnails

my only comment is that when submitting  a new post, its not as clean as it was before.

screen shot 2015-08-11 at 9 52 00 am

**Comment by janelletavares** [comment]
The help text definitely needs to be updated.

**Comment by janelletavares** [comment]
Under edit field_images, change "Enabled browser plugins" to just upload checked.  Likewise, under edit field_video, change "Enabled browser plugins" to just web checked.  That should make it very clear what the user can and should do with these fields.   I don't think anyone really needs access to the 'library' and 'my files' tabs.

Help text should be something like "Select one or more photos to upload" & "Link to at most one YouTube video"

**Comment by janelletavares** [comment]
Bree prefers the sidebar blocks be solid blue, partly because it's most consistent with Acquia.com, but the separation and rounded corners are great.

**Pull request merged**
