### PR TITLE
Post updates and then some

### PR DESCRIPTION
**Pull request by janelletavares**
[AU-675 better help text around office region](https://backlog.acquia.com/browse/AU-675)
 - everyone was confused about what office region was... try to make it clearer

[AU-676 move related event toward the top of the new post form](https://backlog.acquia.com/browse/AU-676)
 - make it clearer that posts can be related to events by putting this field toward the top of the form

[AU-687 the Drizzle on log in page](https://backlog.acquia.com/browse/AU-687)
 - remove 'the' in front on Drizzle on the log in page

[AU-718 Update like flag](https://backlog.acquia.com/browse/AU-718)
 - don't allow unlike
 - change text so it doesn't appear as if lots of people unliked/disliked a post

### CODE REVIEW

**Comment by chris-hamper** [comment]
Reviewing this...

**Comment by chris-hamper** [comment]
Some of the help text doesn't show for non-admin users.  Only way I've found so far to fix this is to enable "View Administrative theme" permission for all authenticated users.  On the plus side, this also makes the Media Browser window look better.

I added a bit of code to hide the text format selector for non-admins, which greatly cleans things up, and brings the moderation notice help text up much closer to the body text box.  Give it a spin and see what you think.

The custom error messages are not featurizable, so your change for AU-687 was lost, I've made the change manually on Prod.

All other user stories look like they're done.

**Comment by janelletavares** [comment]
Will check it out, thanks.

**Comment by janelletavares** [comment]
Argh... we really need that help text about office regions to show up on the authenticated user form.  Can we do a form_alter and change that access on the helper text?

Your changes look good to me.

**Comment by chris-hamper** [comment]
That might work, let me give it a shot

**Comment by chris-hamper** [comment]
Looks like this is theme-related, not permissions related.  Something in the Bootstrap or Acquia Swiss/Drizzle themes is stripping out those descriptions.  Still investigating...

**Comment by chris-hamper** [comment]
Traced it down to the Bootstrap parent theme.  It moves the field descriptions into pop-up tooltips.  There's a checkbox in the theme's settings that can be un-checked to stop that behavior.

I did a merge with master because my local env was throwing errors, and then rebuilt the Theme feature with the setting changed.  All stories should be working now.

**Comment by janelletavares** [comment]
Awesome+++

**Comment by janelletavares** [comment]
@chris-hamper  Form looks much better.  Do you think we would benefit from putting an HL after help text/between fields?  I think that might make it clearer which text does with which input box.  Would be handled in another user story. 

Any objection to merging?

**Comment by chris-hamper** [comment]
Some separation would definitely be a good idea, though I'd prefer simple spacing between fields rather than a line.

**Comment by janelletavares** [comment]
Ok, I'll make a user story to that effect.

**Pull request merged**
