### PR TITLE
Au 596 add wysiwyg to body

### PR DESCRIPTION
**Pull request by dannyacquia**
https://backlog.acquia.com/browse/AU-596

Added WYSIWYG module and CKeditor library.  Also created a feature called drz_wysiwyg_feature

Enable the feature and everything should work.

Just a note, we had to use wysiwyg version 7.x-2.x-dev to get the library to work

### CODE REVIEW

**Comment by allygonthier** [comment]
testing this...

**Comment by allygonthier** [comment]
wysiwg worked as expected with the feature enabled.

**Comment by allygonthier** [comment]
one question, should we also have this enabled for events?

**Comment by dannyacquia** [comment]
It should be included in all body's using the Filtered HTML text format.  I just added it to the article feature to enable wysiwyg initially.

**Comment by janelletavares** [comment]
Yes, enable for events, please and thank you.

**Comment by janelletavares** [comment]
Looks good

**Pull request merged**
