### PR TITLE
AU 691 FAQs

### PR DESCRIPTION
**Pull request by janelletavares**
This pull request adds the module and configures it for the FAQs page.  It does not include the taxonomy configuration, the actual questions and answers, or the link to the Help menu (will all be done directly to the Prod DB)

[AU-691 FAQs](https://backlog.acquia.com/browse/AU-691)

### CODE REVIEW

**Comment by chris-hamper** [comment]
Testing this now...

**Comment by chris-hamper** [comment]
1. Needs major theming help.  Create another user story for this?

Minor issues:
2. The new 'set event_speaker published on date', 'edit terms in faq_categories', and 'delete terms in faq_categories' permissions aren't assigned to any roles.  These should probably at least be assigned to Administrator.
3. The 'additional_settings__active_tab_faq' and 'comment_page' Strongarm variables shouldn't be included in the new feature, as the first frequently changes during use, and the second is unrelated (used for Basic Page content type).
4. Similarly, don't include the 'node-page-body' field.

**Comment by janelletavares** [comment]
I'll fix up the minor issues.  What are you envisioning for theming?

**Comment by chris-hamper** [comment]
Simplest option, we could add the white background to the whole page similar to node pages.

As it stands now, it's not immediately clear what is going to happen when you click on a question link, and the transition when expanding a question is quite jarring.  There's no visual indication that these are expandable-collapsible entities.

We could style each question & answer into its own accordion "box".  It might be possible to do this easily using existing functionality in the Bootstrap theme.  I'd need to poke around to see if that's the case.  Either way, adding a CSS transition would be a fairly simple and nice addition.

**Comment by janelletavares** [comment]
Sounds like you've got some some solid ideas already.  A CSS caret that
flips after clicking would probably make it clear that these questions
expand to show answers.  I think another user story for styling would be
great. This page won't be populated on prod until at least after user
testing, so styling can be put on the roadmap.

**Comment by chris-hamper** [comment]
Sounds good to me

**Comment by janelletavares** [comment]
I'll make the story.

**Comment by chris-hamper** [comment]
@janelletavares have you had a chance to make the minor fix-ups for this?

**Comment by janelletavares** [comment]
Nope, probably tonight.

**Comment by chris-hamper** [comment]
@janelletavares if you haven't had a chance to work on this, I'll go ahead and make the minor changes I listed, test, merge.

**Comment by janelletavares** [comment]
I haven't had the chance, so that's fine with me if you make the changes.
Thanks.

**Comment by chris-hamper** [comment]
Fixed minor issues mention above and added very basic theming

**Pull request merged**
