### PR TITLE
AU-606-607 Updates to new hires views

### PR DESCRIPTION
**Pull request by janelletavares**
https://backlog.acquia.com/browse/AU-606
https://backlog.acquia.com/browse/AU-607

1) Change the relative dates so that Sundays are not counted twice
2) Update the links on the front page block to always go to /new-hires
3) couple css changes to have space around more-link and proper user profile dimensions
4) show 3 new hires on front page and 4 across on /new-hires
5) remove sidebar blocks on /new-hires

Please review!

### CODE REVIEW

**Comment by janelletavares** [comment]
Couple things I noticed, but not sure what to do about them....
1) Long user names are truncated in the blocks.
2) When dragging the browser to be narrower, the new hires results don't always stay in the block

**Comment by allygonthier** [comment]
reviewing this now...

**Comment by allygonthier** [comment]
1) Change the relative dates so that Sundays are not counted twice
confirmed
2) Update the links on the front page block to always go to /new-hires
confirmed
3) couple css changes to have space around more-link and proper user profile dimensions
looks good!
4) show 3 new hires on front page and 4 across on /new-hires
confirmed
5) remove sidebar blocks on /new-hires
confirmed

**Comment by janelletavares** [comment]
Thank you!

**Pull request merged**
