### PR TITLE
AU-528 Add form to configure number of days to look ahead for block listings…

### PR DESCRIPTION
**Pull request by chris-hamper**
…, saving values to Drupal variables.

Change block to use default of caching per-role to avoid possible security issue.

### CODE REVIEW

**Comment by chris-hamper** [comment]
The number of days ahead to list birthdays and anniversaries can be changed now by going to the Blocks page and clicking the "configure" link next to the Birthdays or Anniversaries block, or using the gear icon on those blocks.  Each block has its own separate setting for number of days to show.

**Comment by chris-hamper** [comment]
I'm going to tack on a commit to add the new Drupal variables used by these blocks to the existing Birthdays & Anniversaries feature, so those will get version-controlled.  Please wait for that before testing.

**Comment by chris-hamper** [comment]
Featurization fix completed. This is ready to test.

I belatedly created a story for this issue: AU-528

**Comment by chris-hamper** [comment]
@janelletavares @ndelrossi @allygonthier @sonyablade87 @dannyacquia  can one of you test this and merge?
Thanks

**Comment by janelletavares** [comment]
I'll do it sometime before I leave the office today.

**Comment by janelletavares** [comment]
Form looks great!  I see these blocks on the front page without them appearing as enabled on the blocks page... how is that happening?

**Comment by chris-hamper** [comment]
Control of block placement is done by Contexts now, since the Bock
configuration screen is not featurizable. There is a default context that
places blocks for all pages, unless overridden by another context.

-- 

Chris Hamper* | *
*Acquia University** |*

* Acquia
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>
*

*M:* 413-464-4280
*E: *chris.hamper@acquia.com <chris.hamper@acquia.com> | Skype: hampercm
W: http://www.acquia.com
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>

53 State St., 10th Floor, Boston, MA 02109

**Comment by janelletavares** [comment]
Ah, I didn't have the context UI module on, so I didn't easily find that.
Makes sense!

**Pull request merged**
