### PR TITLE
AU-728 link birthdays to profiles

### PR DESCRIPTION
**Pull request by chris-hamper**
Links names to user profiles in Birthdays and Acquiaversaries blocks. 

Adds custom caching for both blocks, as Drupal's default block caching wasn't working for unknown reasons.

### CODE REVIEW

**Comment by chris-hamper** [comment]
Hold off on testing this for a minute...

**Comment by chris-hamper** [comment]
OK, all set now.  I had also added a check to the Context feature to prevent the sidebar blocks from being added to Admin pages

**Comment by janelletavares** [comment]
Will look today

**Comment by janelletavares** [comment]
Looks good!

**Pull request merged**
