### PR TITLE
Misc styling

### PR DESCRIPTION
**Pull request by janelletavares**
So as to not create unnecessary conflicts in our CSS file, I did a bunch of styling in one pull request.

[AU-655 Update no results styling for past and upcoming events](https://backlog.acquia.com/browse/AU-655)

[AU-656 update user tags list to take up less space](https://backlog.acquia.com/browse/AU-656)

[AU-665 User profile styling](https://backlog.acquia.com/browse/AU-665)
 worked on subtasks to put a white background and black outline around the user profile fields.  could still do something to make the user's posts view look prettier in another user story

[AU-669 restyle new hire archive](https://backlog.acquia.com/browse/AU-669)
bold instead of italics, centered

[AU-670 style full event node page](https://backlog.acquia.com/browse/AU-670)
fewer font sizes, a bit of spacing

[AU-712 replace green with orange in the footer](https://backlog.acquia.com/browse/AU-712)
cleaned up the menus a bit and changed the color.  apparently, branding is moving to just black, white, blue, and orange

[AU-713 move featured event to header and make it orange](https://backlog.acquia.com/browse/AU-713)
This looks pretty good in authenticated user view.  I got some feedback from Bree about it.  Because of the admin bar at the top, it doesn't look great for admins... the navbar covers it.  Work in progress, but worth pushing in some form now.

[AU-716 reduce roundness of corners](https://backlog.acquia.com/browse/AU-716)
Some user feedback was that the corners were too round...

[AU-723 employee count](https://backlog.acquia.com/browse/AU-723)
consistent font size, make ...and counting the link rather than the number

[AU-734](https://backlog.acquia.com/browse/AU-734)
shorten text and center

I also tried to organize the CSS a bit by category.   Please review!

### CODE REVIEW

**Comment by janelletavares** [comment]
Also, this covers AU-693

**Comment by janelletavares** [comment]
I'll get to the merge conflicts eventually...

**Comment by chris-hamper** [comment]
Ugh, the merge conflicts on the CSS file are a mess.  I'd suggest reverting that last commit (though it looks like there might be at least one change in there that isn't simple reorganization) and putting off the reorg until after the merge.  Or even better, break the CSS out into multiple files.

**Comment by chris-hamper** [comment]
No point in testing this until after that is done, as we'd be testing something that might just get broken during conflict resolution

**Comment by janelletavares** [comment]
I'll take care of the merge.  The behavior will be the same now as after
the merge.

**Comment by chris-hamper** [comment]
We really need to do a merge with master before testing this, and I'd again recommend reverting most of that last commit for now.  If you take a look at the merge conflicts, you'll see what I mean.  Any mistakes in the merge, and the entire theme's styling could get fubared.

**Comment by janelletavares** [comment]
I will take care of it.  Each commit is merged one at a time with a
rebase.  Conflicts will be handled before getting to the last commit.  I'll
evaluate how to handle it.

**Comment by chris-hamper** [comment]
In that case, please do the rebase now, and force-push the branch back up to GitHub

**Comment by janelletavares** [comment]
I'm working on something else now, so I'm not going to get to it just yet.
If you have time for Drizzle now, I suggest looking at branches #108 or
#112.  Or making your updates to #114.

**Comment by janelletavares** [comment]
I did a fetch and rebase off master.  Fixed all the conflicts one commit at a time.  I think it all still looks as I intended.  Force pushed, so it should be good to go for a review.

**Comment by janelletavares** [comment]
+AU-737

**Comment by chris-hamper** [comment]
Thanks for taking care of the conflict resolution, Janelle.

Some issues / suggestions I came up with:
- Upcoming Events block in sidebar shows an empty white box with green border when no events are upcoming
- Names in User Tags autosuggest results are links that take you to profile when linked. This causes unexpected behavior. (Not sure if caused by this branch specifically)
- User's posts view on profile pages not styled like rest of profile (already mentioned above)
- Highlighted event doesn't show properly on front page (already mentioned above)
- New Hires block not showing
- New hires grid doesn't reflow to single column on mobile screen widths
- Space above Event Links
- Float Registration Link to right? or space them out to improve touch screen UX
- Attendance button wording is ambiguous:  am I attending already, or do I need to click to attend?  Do I still need to register/cancel at the Registration link?
- Style Attendees block
- Scroll down to Attendees block when the button is clicked (or even better use AJAX?)
- Attendance button and Like link/button are merged into one box

**Comment by janelletavares** [comment]
Thanks for the review.

Responding as if numbered...
1) will definitely take a look at this and fix it
2) might just be a matter of changing the type... will take a look
3&4) mmhmm other than a white box, not sure what else we might want to do here?
5) new hires block is not supposed to show on the front page anymore when it's empty, per Heather Hartford.  One can get to the new hire archive by clicking "...and counting" in the footer
6) something to take care of in the mobile user story?
7 & 8)  Above Event Link and Registration Link in the event node view? That would look nice.
9) These are the words that Bree requested.  I think the user will understand that the button is more actionable than the previous link.  When they click, the page will reload and they will immediately appear under attendees.  The registration link will rarely be populated, and the event text will make it clear who can attend which events.  For example, almost no one can attend DrupalCon Barcelona.
10) Can you be more specific?
11) I don't know how to do that
12) why do you think that's the case?

**Comment by chris-hamper** [comment]
5) I think it wasn't showing, even when there were new hires, but I could be wrong. Will re-test.
9) Perhaps hide Attend button when there is a Registration link? Style button to have different text on hover to clarify state vs. action of button.  Could run this by Bree.
10) Style in white blocks like other main content
11) Theoretically: create anchor in the view header, and link to that in the button.  We can tackle this in AU-614
12) Probably just used the wrong CSS selector for the task - should be easy fix

**Comment by chris-hamper** [comment]
I'll start working on resolving the issues I identified, leaving the ones that should be discussed further as-is.  I really want to get this one merged ASAP

**Comment by janelletavares** [comment]
9) The attendance button is an unoffical, social, Acquia, Drizzle thing and
the registration link is an official event thing.  They're different, so I
don't think we should have a relationship between them in the code.  Event
admins are very aware of using the event registration link field
judiciously.
12) The like flag for an event is in a different pull request.  The
attendance flag and the like flag could not be merged into one box.

**Comment by janelletavares** [comment]
9) Hover text might be nice

**Comment by chris-hamper** [comment]
- New hires block does seem to be showing correctly
- Fixed button-ification of flags.  Also made Like flag into button, as it seems like consistency makes good sense here for UX
- Fixed positioning of featured event
- Fixed styling of Upcoming Events sidebar, added border and backgroud styling to Attendees, and User's posts blocks to match rest of page

**Comment by chris-hamper** [comment]
Should be ready to test and merge.  Still to do:
- Scroll down to Attendees block when the button is clicked (or even better use AJAX?)
- Names in User Tags autosuggest results are links that take you to profile when clicked. This causes unexpected behavior.
- New hires grid doesn't reflow to single column on mobile screen widths (added to AU-515)
- Attendance button hover text

**Comment by janelletavares** [comment]
Testing now...

**Comment by chris-hamper** [comment]
Ugh, erroneously started closing related issues :P  Think it's time for a break :)

**Comment by janelletavares** [comment]
After I fetched, rebased and refreshed...

Like button looks good.
Spacing around links looks good.
Users posts look good.

'posts about this event' does not have a background
screen shot 2015-09-14 at 3 24 06 pm

attendance button is no longer centered.  Bree specifically asked that is be centered.  Are you seeing something different?  There's shouldn't be a like button for events yet in the pull request.
screen shot 2015-09-14 at 3 25 49 pm

I really dislike the new position of the featured event block.  It's needs to go back up under the navbar, but adjust to the admin bar.
screen shot 2015-09-14 at 3 26 31 pm

Featured event is still showing up in the footer!
screen shot 2015-09-14 at 3 27 58 pm

**Comment by chris-hamper** [comment]
The featured event isn't showing in the correct location on your environment, it should be up higher where you'd want.  Pretty sure the button is centered in a different branch.  It's also possible you need to do a local merge with master to get everything in sync.

**Comment by chris-hamper** [comment]
Ugh, I forgot to featurize the Context change, that's what the problem is with fetured event.

**Comment by chris-hamper** [comment]
Hmm, maybe it was this PR that centered the button, having trouble keeping track at this point.  No idea why it stopped centering, though, as I don't think I touched any CSS that should have changed that.  But, If we're adding a like button to events, is centering the Attending button the right way to go, anyway?  I'll try to track down what broke centering in the meantime...

**Comment by janelletavares** [comment]
If there's going to be two buttons instead of one button and a link, then
centering would not make sense anymore.

**Comment by chris-hamper** [comment]
Found it...  I had changed where the button CSS classes were getting attached to fix the smerging of links into one "button" which wasn't a button.  That change had broken the centering.  Guess it's moot though.  I'll put the Attendance button left-aligned, anticipating the Like button on the right.

Also adjusted styling for the Posts About This Event block.

**Comment by dannyacquia** [comment]
Everything looks good.  I went through each commit and checked the code and the associated item on the pages.  I made a couple notes that should maybe go into user stories that can be done at a later time.

For now, it is good to merge.

**Pull request merged**
