### PR TITLE
Instead of hybridauth being accessible by everyone, only let it be ac…

### PR DESCRIPTION
**Pull request by janelletavares**
…cessible for anonymous users, user admins, and site admins

### CODE REVIEW

**Comment by chris-hamper** [comment]
Hmmm, it looks like users can't change their HybridAuth settings anymore, but the tab on the user profile page is still there, even with the permission removed.  I'll push a commit to fix this.

**Comment by chris-hamper** [comment]
@janelletavares can you test to make sure this hides the tab for auth users?  Looks good to merge after that

**Comment by janelletavares** [comment]
I'll take a look today.  Thanks!

**Comment by janelletavares** [comment]
Confirmed, tab is gone.  Much better, thanks.

**Pull request merged**
