### PR TITLE
Use one widget to upload images or embed youtube videos with optional…

### PR DESCRIPTION
**Pull request by janelletavares**
The task was to allow authenticated users to embed videos with optional captions.

I used media and media youtube modules to create a single interface for uploading images and embedding youtube videos.  This is nicer than have separate buttons and fields for images.  Also, the image field did not previously allow for multiple images, so this more thoroughly fulfills that user story.  I had to manually add office regions to make any test articles.

@ndelrossi  Please review.

PS Git and features are the banes of my existence.

### CODE REVIEW

**Comment by ndelrossi** [comment]
I am trying to review this but running into problems in the process.

The drz_articles features is saying it is missing dependencies and needs to be rebuilt?: "Unmet dependencies: field_collection (Missing), media (Missing)"

Also I assume this update requires the Media module but this pull request does not include those files. It does not seem like the Media module was installed before this PR either.

**Comment by janelletavares** [comment]
This might be the situation where I have to manually specify a
dependency... let me check.

**Comment by janelletavares** [comment]
media and field_collection are already part of the dependencies array...

more drz_articles.info

name = Drizzle Articles Feature

description = Settings for the Article content type

core = 7.x

package = Drizzle

version = 7.x-1.0-alpha1

dependencies[] = features

dependencies[] = field_collection

dependencies[] = image

dependencies[] = image_field_caption

dependencies[] = media

dependencies[] = strongarm

dependencies[] = taxonomy

dependencies[] = text

features[ctools][] = strongarm:strongarm:1

...

**Comment by janelletavares** [comment]
I'm reworking the whole thing with Ted... please stand by.

**Comment by janelletavares** [comment]
I have updated the branch, but it's probably not perfect yet.  Don't spend too much time on it, but let me know if you try it and it works/doesn't work.  I'll revisit it tomorrow afternoon... the contrib modules aren't tightened up yet.  

Reminder: upon bringing in the branch, run...
`drush fr drz_articles`
`drush updatedb`
before test

**Comment by janelletavares** [comment]
hybridauth doesn't want to be enabled sometimes, but everything in drz_articles should be on point now.

**Comment by chris-hamper** [comment]
I'll test this out.

**Comment by chris-hamper** [comment]
@janelletavares I can't seem to get this working on my local env. Please ping me when have some time to go over this with me.

**Comment by chris-hamper** [comment]
@janelletavares  I ran the database update this time, and things looked better. The Media field is working, and I can upload images and youtube video links. Here are some problems I noticed:

1. It's still not clear to me how to add a caption to an image.

2. The Media field isn't displayed in the Teaser views on the front page, etc.  In the "Manage Display" interface for the Article content type, that field is marked as hidden.

3. The trim length for the Body field in the Teaser view doesn't match the value we have on production (should be 100).

**Comment by janelletavares** [comment]
Thanks for the feedback.  I'll take care of this on Monday and mark it as
Sprint3.

**Comment by janelletavares** [comment]
I think it's ready for review.  "drush fra -y" and "drush updatedb" should be sufficient after a pull and branch checkout to have all the updates.  If you still see an image field in Article content type, we're just going to have to delete it manually in all the environments.  

I made it so that images and videos are the same width (640px) in the teaser and in the article view.  I like the way this looks, and it requires that some small images be scaled up.  If scaling up is undesirable, let me know and I'll change it to not autoscale up.  Also, the image may be scaled down to be easily viewed, so I made it such that a Drizzler can click on the image to see it as max pixels.

**Comment by janelletavares** [comment]
I think this is as good as it's going to get.

**Comment by chris-hamper** [comment]
I've tried to test your latest, but keep getting "broken link" images for the thumbnails in the media browser window.  The images do display correctly in Teaser and Full view, so I'm not sure what's going on.
screenshot-media-thumbnails

**Comment by chris-hamper** [comment]
Arg. I was hoping perhaps the thumbnails would show OK as a plain user, but things got worse.  This is the result when I tried to add media:

screenshot-auth-user

**Comment by janelletavares** [comment]
Very strange! I've never seen that. Thanks for looking. We'll figure it out tomorrow.


-------- Original message --------

**Comment by chris-hamper** [comment]
I rebased your branch from GitHub up to master last night as I was trying
to resolve the broken image problem. If you'd like to work from there, I've
pushed it to GitHub as a new branch:

rebase-AU-501-embed-video-with-caption

-- 

Chris Hamper* | *
*Acquia University** |*

* Acquia
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>
*

*M:* 413-464-4280
*E: *chris.hamper@acquia.com <chris.hamper@acquia.com> | Skype: hampercm
W: http://www.acquia.com
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>

53 State St., 10th Floor, Boston, MA 02109

**Comment by janelletavares** [comment]
I've pulled in your rebase branch to retest.  I haven't reproduced either of your problems.

When all features aren't enabled, I'm not able to get to /frontpage.  Maybe that would explain your unauthorized access problem.

I don't have a problem with broken images - whether teasers, full view, or thumbnails.  What's the public file system path in your test environment?

**Comment by janelletavares** [comment]
I did a pull to sync with master.  Maybe things are working better now.  Perhaps the fact that this branch could be automatically merged now is a good sign!

**Comment by chris-hamper** [comment]
The thumbnails are working on my local now, so that's good :)
There are still a few problems:

- Plain users can't use the Media browser, they need to be granted 'use the media browser' and 'view the administration theme', since Media browser uses the admin theme
- Even with those two permissions, users can't upload new images or video links.  Not sure why yet.
- The Media field is still set to use the public file system. This needs to be changed to use the private file system instead, which can only be done when there is no data on any content in the media field.  So, to switch this, you'll need to grab a fresh copy of the DB from Stage, reenable the features and revert them, and then you should be able to change the file system setting for Media field in the Articles content type at:  /admin/structure/types/manage/article/fields/field_file/field-settings
- Also enable Private files under "Allowed URI schemes" at:
http://drizzle0.dev.dd:8080/admin/structure/types/manage/article/fields/field_file
- Change the file directory on that same screen to use something other than blank, perhaps "articles/media".  This should narrow down what users will be able to see in the Media browser, rather than allowing them to poke around the entire private file system.

**Comment by janelletavares** [comment]
Thanks for the thorough feedback.  I'll get right on it.

**Comment by janelletavares** [comment]
I thought we didn't want to 'allow private file' under allowed URI schemes
because that prevents people from uploading videos rather than embedded
videos hosted elsewhere, but we have file upload restrictions so that's not
a real problem.  When I click that, I can specify the file directory. So,
that's all good.

I fixed the permission so an authenticated user can upload images and video
urls.  I didn't have to enable 'view the admin theme'.  I also removed the
library view from authenticated users.

I updated the rolls/permissions features to include the newly specified
permissions here.  Also, removing the image field in favor of media caused
an issue for the user posts view. I made the minimal changes to the view to
resolve the conflict.  Pushing to the branch soon.



On Wed, Jul 15, 2015 at 2:08 PM, Janelle Tavares <janelle.tavares@acquia.com

**Comment by chris-hamper** [comment]
I don't think enabling 'Private files' under 'Allowed URI schemes' will interfere with linking to videos.  It doesn't seem to break that on my local.  We definitely need it enabled since we'll need to use the private file system based on our project's requirements of being accessible only by Acquia employees.

We should add 'gif' to list of allowable extensions for that field, as well.  Just noticed that wasn't there.

**Comment by janelletavares** [comment]
That was something that I was going to ask Bree about today.  There may be
feelings one way or another about whether or not gifs are content wanted on
Drizzle.  Some people find them less than classy...

**Comment by chris-hamper** [comment]
We do have moderators for that same purpose, but I definitely see your point.  Maybe ask Bree her opinion?

And, I misread your previous post.  I didn't see it was about *uploading videos* breaking, not *video links.*  It's generally tricky to serve videos directly from your website, as they can quickly eat up bandwidth and CPU/disk resources, so restricting to use only links to videos is probably a good idea anyway.

**Comment by chris-hamper** [comment]
@janelletavares Looks like this one is almost there :)  add gif to allowed extensions and I think we're good to merge

**Comment by janelletavares** [comment]
Np, thanks Chris!

**Comment by chris-hamper** [comment]
@janelletavares I added a quick patch to enable required preview of Articles and disable the option to add an Article to the Main Menu.  I've tested it, but feel free to test or not, and merge either way!

**Comment by janelletavares** [comment]
Looks good!  I'm really glad this will be part of the next demo.  Thanks, Chris.

**Pull request merged**
