### PR TITLE
[Urgent] Add user import functionality and 'user admin' role:

### PR DESCRIPTION
**Pull request by chris-hamper**
- Configure private file system path
- Add User Import contrib module
- Enable import of date fields using hook_field_user_import_supported_alter in drz_custom module
- Add 'User admin' role and all permissions not yet under feature control
- Clean up display of birthday and anniversary fields on user profile, add dependency to Date Popup widget
- Add dependency to User Import to Birthdays and Anniversaries feature, change human-readable name

### CODE REVIEW

**Comment by chris-hamper** [comment]
See me for instructions on how to test the import functionality

**Comment by janelletavares** [comment]
I can take on reviewing this.

**Comment by janelletavares** [comment]
I made a fake user-admin acct to see how it would look to use.  Since there's no administration privileges on this account, which makes sense, we should keep tracking of making a special view/interface for this admin to import new users - perhaps just a main menu link that is only visible for this account to admin/people/user_import/add.  If that sounds like a good idea, I can add that to my main_menu branch.  Let me know, @chris-hamper.

Generally, looks to be significant progress in the right direction.

**Comment by janelletavares** [comment]
Go ahead and merge whenever you want.

**Pull request merged**
