### PR TITLE
Au 539 update admin view

### PR DESCRIPTION
**Pull request by allygonthier**
I added the admin view and also created an updated view for admin/content.
I also updated the drizzle view feature and this is also my first time trying to featurize a view so not sure if this can through correctly.

### CODE REVIEW

**Comment by chris-hamper** [comment]
Did a merge with master to resolve conflicts.  Please pull this branch from GitHub before making local changes.

**Comment by chris-hamper** [comment]
Testing this...

**Comment by chris-hamper** [comment]
@allygonthier This is a good start, but you'll need to add both a field and an exposed filter criterion for the "office region" field to the "Adminstration: node" view.  That will allow an admin to see and filter content by region, which are requirements of AU-539.

**Comment by allygonthier** [comment]
ok it seems that this is a  known issue with admin views, so I cloned my admin view and named it admin_content.  I was then able to successfully featurize this (I hope).  Please try this again @chris-hamper!

**Comment by chris-hamper** [comment]
It doesn't look like the new view got featurized at all this time.  Perhaps we can step through this issue together to figure out what's going wrong?

**Comment by allygonthier** [comment]
bummer, I really thought the view had been featurized so yes lets get together on this one.

**Comment by chris-hamper** [comment]
Testing latest...

**Comment by chris-hamper** [comment]
Looks like this is good :)  I discovered a bug that was actually causing the link to /admin/content to disappear completely from all menus when this branch was applied.  I was able to trace this to a bug in Admin Views (it was related to those PHP notices I was seeing), and worked out a workaround for it.  

**When this branch gets applied on a new environment (i.e. Cloud Dev and Stage), we'll need to do the following steps:**

1. Go to the Views list and disable the "Administration: nodes" view that comes with the Admin Views module
2. Edit the "admin/content" view that Ally created
3. Drop down the "Advanced" section and edit the "Path"
4. Don't change anything, just click "Apply"
5. Save the view, you should no longer see the PHP notices

**Comment by janelletavares** [comment]
Wow, nice work, Chris!

**Pull request merged**
