### PR TITLE
AU-498 -499 Birthdays and Anniversaries blocks

### PR DESCRIPTION
**Pull request by chris-hamper**

### CODE REVIEW

**Comment by allygonthier** [comment]
testing

**Comment by allygonthier** [comment]
this looks great!  moving over to testing.

**Comment by ndelrossi** [comment]
I'm having problems testing this. I did a features-revert-all, updatedb, and cleared cache twice. Getting this error on all pages. Any ideas @chris-hamper ?

screen shot 2015-07-11 at 11 18 11 am

**Comment by chris-hamper** [comment]
@ndelrossi Did you do a "drush cc all" and then "drush fl" to check if all the features were enabled before you did the feature revert?  Here's the workflow I used (Note: you may have a different git remote from mine, which is 'github'):

1. git checkout github/AU-498-499_birthdays_aniversaries_views
2. [restore database from a recent Acquia Cloud Stage backup]
3. drush cc all
4. drush fl
5. [enable all disabled Drizzle features with drush en -y ...] (don't enable Date Example or Features Test)
6. drush fra -y
7. drush cc all
8. drush cc all
9. drush uli

**Comment by ndelrossi** [comment]
Thanks Chris! Working great now. I think I forgot to enable the new feature. I'm merging it in.

**Pull request merged**
