### PR TITLE
Main menu updated

### PR DESCRIPTION
**Pull request by janelletavares**
This branch removes the home link and adds a 'New Post' link on the main menu that everyone can see.
Also, it puts User Admin and User Import links on the main menu just for the user admin role using the menu_by_role module.  If there's a better way to do it, let me know.

### CODE REVIEW

**Comment by janelletavares** [comment]
Menus aren't easily featurized... might have to write some code in the feature for this.  Stay tuned.

**Comment by janelletavares** [comment]
It might already be done in stage, but the home tab in the main menu will have to be removed manually.  I can't find the means to do it via hook_menu_alter().

**Comment by chris-hamper** [comment]
[menu_link_delete](https://api.drupal.org/api/drupal/includes!menu.inc/function/menu_link_delete/7) inside an install or update hook would probably do it, but as it's already removed on Stage, no need to worry about it.

I'll test this out and merge...

**Comment by chris-hamper** [comment]
@janelletavares You shouldn't need a module to prevent access to Admin pages, as Drupal's built-in permissions system will automatically hide menu items that are not accessible to the current user.

**Comment by janelletavares** [comment]
Somehow I missed menu_link_delete.  It was easy enough to figure out the
path to the link I wanted to remove.  Now, the feature should be complete
and precise, so everyone's environment looks the same.

Ah, you are very right!  I was playing around with the admin and user admin
accounts, both of which have access to user import so I could always see
the link and incorrectly extrapolated that all accounts could see the
link.  I do see that no additional settings are needed to hide this link
from authenticated users and content admins. That makes it easier!  Just
pushed the updates to the branch.

**Comment by janelletavares** [comment]
To update the summary, this branch removes the redundant Home link, adds a New Post link that everyone can see, and adds a User Import link that only user admin and admin accounts can see, not content admin or authenticated users.

**Comment by chris-hamper** [comment]
Looks good :+1:

**Pull request merged**
