### PR TITLE
Au 572 show author and publish date

### PR DESCRIPTION
**Pull request by dannyacquia**
https://backlog.acquia.com/browse/AU-572

Do not merge this until after 563 is merged.

This is just a template change.

### CODE REVIEW

**Comment by janelletavares** [comment]
I hope you're planning not to do this branch dependency thing again.  It complicates review, and obviously merging.

The new string is a little misleading/inaccurate, as publisher/approver is a content admin and not the authenticated user/author of the content.  Also, I don't like the new date format, would prefer something with a day of the week and words rather than all numbers and slashes - a shortened version of the long date format without the time.  No time of day looks cleaner, so I like that.

 I would prefer something more like...

+      <?php print 'Authored by ' . $node->name . ', published on ' . format_date($node->published_at, 'custom', 'D, M j, Y');?>

**Comment by dannyacquia** [comment]
Okay, I've made that change for you.  And yes I will try not to have this nested garbage.  I just kept getting merge errors.  I'll find a way around it next time.

**Comment by janelletavares** [comment]
Thank you, looks good

**Comment by dannyacquia** [comment]
Okay, can you review this now that it is merge ready and make sure nothing is wrong.

**Pull request merged**
