### PR TITLE
AU-588 -584 views caching

### PR DESCRIPTION
**Pull request by chris-hamper**
Front page and events views will be cached for up to 6 hours, or until a Post or Event changes, respectively.

Other views will be cached for at least 1 min, or up to 6 hours if no changes are made.

Admin views shouldn't be cached at all.

### CODE REVIEW

**Comment by janelletavares** [comment]
Will take a look today

**Comment by janelletavares** [comment]
Some comments in line.  After pulling and testing, everything seems to work fine from the admin perspective.

**Comment by chris-hamper** [comment]
Some of the permissions might need to be fixed, as those were simply committed as they are configured currently, and many changes are done in other branches , which should fix permissions for the event admin role. I'll take a look at them and push up a commit to fix.

**Comment by chris-hamper** [comment]
Reverted featurized comment permissions, as those will be added by #108 anyway.  Event admin role doesn't exist in master yet, so can't add those permissions here.  #106 should fix that when it's merged

**Comment by janelletavares** [comment]
Looks fine to me

**Pull request merged**
