### PR TITLE
removed tag field and updated menu

### PR DESCRIPTION
**Pull request by allygonthier**
@janelletavares

### CODE REVIEW

**Comment by janelletavares** [comment]
I'm going to commandeer this branch.  Removing the Post link was overzealous, and the code to remove the tags field never seems to have gotten called.  I'll figure it out.

**Comment by janelletavares** [comment]
It's hard to get the .install file to run.  I'm going to need someone else to give this a try.  We may just abandon this branch altogether and do these things manually. @allygonthier

**Comment by allygonthier** [comment]
ok gotcha, @janelletavares let me know if I can do anything on my end to help you here!

**Comment by janelletavares** [comment]
@allygonthier If you would pull in the updated and test them locally, that would be great.

**Comment by janelletavares** [comment]
something went awry with this branch.  I'm going to make a new branch for the changes to drz_articles.install and maybe drz_menu_features.features.menu_custom.inc

**Pull request closed without merging**
