### PR TITLE
AU-689-690 user and help menus

### PR DESCRIPTION
**Pull request by janelletavares**
Styling and attempted to featurize.  Will recreate on Prod manually eventually.  Will take a look at making the caret blue today.

### CODE REVIEW

**Comment by chris-hamper** [comment]
Found some issues:
1. The FAQs and Contact links in the help menu link to the front page instead of /contacts and /faqs
2. The Profile menu item looks like it's pointing correctly to /user, but clicking on it doesn't cause any action at all
3. The 'My Account' menu item is still shown. Here's the end result:
screen shot 2015-09-23 at 12 28 50 pm

4. Several footer menu items now have both old and new versions shown:
screen shot 2015-09-23 at 12 31 01 pm

**Comment by janelletavares** [comment]
1) Does /contacts exist already?  /faqs does not exist in this branch yet,
so I can't set it to a link that doesn't exist.
2) I'll look into that.
3) I guess that would require some code to try to remove menu links, or not
bother since it all has to be manually reconfigured on Prod anyway.

1.1) that's appears to be a DB hiccup... I don't see that locally.

**Comment by chris-hamper** [comment]
Looking at the feature code directly, those are pointing at <front>

It may be best to just consider Menus as content, since they can't really be featurized reliably from what I can tell.  This would mean not bothering trying to featurize the menu items, and simply making sure CSS styling and Context changes are in code.

**Comment by janelletavares** [comment]
Should we get rid of the drizzle_menu feature altogether?

**Comment by chris-hamper** [comment]
Yes, lets take drz_menu_features out completely.

**Comment by janelletavares** [comment]
Will do

**Comment by janelletavares** [comment]
I've updated the contact us link to contacts.
I will update the FAQs link to faqs after that branch is merged.
I've removed the menus feature altogether. 
Fixed the color of the caret.
The Profile menu link only works for me sometimes... still investigating that.  Will push changes as soon as that is resolved.

**Comment by janelletavares** [comment]
I've added the special menu items module to create a nolink menu item.  That can be used to sort Acquia Links in the near future, as well.

How's this?

screen shot 2015-09-25 at 12 00 30 pm

**Comment by chris-hamper** [comment]
Looks good to me.  Did you figure out the issue with the "My Profile" link?

**Comment by chris-hamper** [comment]
Replacing with #144 to fix weirdness via a the user_menu_fix branch

**Pull request closed without merging**
