### PR TITLE
AU-717 No more shadows in links

### PR DESCRIPTION
**Pull request by chris-hamper**
Removed text shadows and styled links in blocks to conform with styling on acquia.com

I also made all fields in the Events views blocks link to the event node (rather than just the title) to improve UX.  Events pages were left as-is.

### CODE REVIEW

**Comment by janelletavares** [comment]
I'll review

**Comment by janelletavares** [comment]
I like the links for all event fields.

I'd like to keep some kind of hover behavior for the links in the blocks.  I liked hover { color: black; }, but we could do something more subtle like what happens when you rollover Drizzle at the top or one of the Post titles.

**Comment by chris-hamper** [comment]
There actually isn't nearly as much hover going on as there used to be on Acquia.com, and generally no hover effect at all for white text on a colored or black background.  I'd like to stay consistent with that if possible, as there is a company-wide push to maintain or increate consistency with the new style guide used there.

**Comment by janelletavares** [comment]
I asked Bree today, and she likes the hover to black behavior.  Seems like
we'll have to discuss it further.

**Comment by janelletavares** [comment]
Discussed with Bree.  Ready to merge.

**Pull request merged**
