### PR TITLE
added better exposed module and feature for updated view

### PR DESCRIPTION
**Pull request by allygonthier**
I updated the feature for the front page view so that it included an exposed filter for both region and jump to date.  I also added a new module to remove the "Apply" for both fields.

### CODE REVIEW

**Comment by janelletavares** [comment]
@allygonthier Will review today

**Comment by janelletavares** [comment]
Something is awry...  The filter has a broken link.  All features are reverted and enabled.
screen shot 2015-07-21 at 4 22 23 pm

**Comment by allygonthier** [comment]
ok I see.  the date_views module needs to be enabled for this filter.
not sure how this can be featurized?

**Comment by janelletavares** [comment]
You can add an explicit dependency in the feature.  I can work with you
offline to show you how to do that.

**Comment by janelletavares** [comment]
There may be a way to do it in the UI, as well.

On Wed, Jul 22, 2015 at 9:18 AM, Janelle Tavares <janelle.tavares@acquia.com

**Comment by chris-hamper** [comment]
@allygonthier you can explicitly list a module as a dependency by expanding the "Dependencies" section when creating/recreating a feature and checking the box next to the module's name.  That way the module will always be enabled when the feature is enabled.

**Comment by allygonthier** [comment]
thanks @chris-hamper  & @janelletavares !  I have added this as a dependency as you both suggested.

**Comment by janelletavares** [comment]
It's enabled by default now, which is much better.

I see an issue with the view.  The granularity of the sort criteria on date changed to month, but that should stay as second.  Do you think there's any interest in being able to select more than one region in the filter?

**Comment by allygonthier** [comment]
ok thanks!  @janelletavares, please try again.

**Comment by janelletavares** [comment]
Looks good!  Thanks for the updates.

**Pull request merged**
