### PR TITLE
change the image and iframe styles on the front page to have maxwidth…

### PR DESCRIPTION
**Pull request by dannyacquia**
… of 100%

https://backlog.acquia.com/browse/AU-565

Just need pull the code for the css change.

### CODE REVIEW

**Comment by janelletavares** [comment]
This change doesn't scale the image, but skews it to make it fit in the column.  That doesn't look good.  A change also needs to be applied to the Article node view, the Event node view, and the upcoming and past events views.

**Comment by dannyacquia** [comment]
Okay, the newest commit should fix the scale issues.  The height on the video window can't be scaled with auto or it makes the player super small.  But the video itself auto scales with the width.  There will just be a little black area above and below the video.

**Comment by janelletavares** [comment]
I'll get to checking it out again tomorrow morning, most likely.

**Comment by dannyacquia** [comment]
Okay, I just added a module called fitvids and added it to this branch.  It makes all embedded videos responsive no matter where they are on the site.

You should just have to update your drz_articles feature and the fitvid module will automatically enable.

**Comment by janelletavares** [comment]
Super cool

**Comment by janelletavares** [comment]
Front page looks good.  Would you apply these changes to the events views, or would you prefer that be another user story?

**Comment by dannyacquia** [comment]
It should already apply to all pages

**Comment by janelletavares** [comment]
Hmmm let me take a screenshot

-------- Original message --------

**Comment by janelletavares** [comment]
I just needed to run update again.  Now events look good, too.  Thanks!

**Pull request merged**
