### PR TITLE
Turning on the contact module and styling it to fit with the rest of …

### PR DESCRIPTION
**Pull request by dannyacquia**
…the site

https://backlog.acquia.com/browse/AU-705

Need to revert for the permissions feature and the rest is a new template file for page--contact.tpl.php and css changes.

The url is /contact but no links have been added yet in the menus.  Waiting on the help link dropdown.

### CODE REVIEW

**Comment by chris-hamper** [comment]
Ahh...the page--contact template file, that's what was in the nebulous part of my memory yesterday afternoon, regarding altering that :)  Testing this now...

**Comment by chris-hamper** [comment]
Some minor issues:
- $title_prefix, $title, and $title_suffix need to all be rendered within the same wrapping element; you have _prefix split outside the wrapper
- I'm concerned about the brittleness of using acquia_drizzle_preprocess_page() to change the title the way you've implemented it.  Since we're overriding the template anyway for this specific page, how about we hard-code the title there?  It shouldn't affect personal contact forms needed later.

- Nitpick: try to always PHPDoc your functions, as per Drupal coding standards. PhpStorm makes this very easy. (admittedly, I've not done this a time or two :) )
- Would be nice to have the btn-primary CSS class attached to the button to make styling more visible.  Not sure if it's worth effort, up to you

**Comment by dannyacquia** [comment]
I made the changes you suggested.  Looks like we have some merge conflicts now.  Can you test it for now and then I'll work on merge conflicts after you verify it is fine?

**Comment by chris-hamper** [comment]
Looks good. Needed to merge with master anyway to test, so I pushed that up.  Merging...

**Pull request merged**
