### PR TITLE
First pass at all Events support

### PR DESCRIPTION
**Pull request by janelletavares**
There are a lot of little things in this branch, so it might be nice to review this together during the stand up.

1) new content type for event
2) two new taxonomies for the event content type (fun/community and core DNA)
3) entity reference from article to event (associate event with post of photos/videos/reactions)
4) entity reference from event to event (last event in series)
5) entity reference within field collection in event (speakers and their talks)
6) new blocks for next ten fun events and next ten community events on all pages
7) new page with all events, sorted by start date and sticky
8) update front page view to not include events
9) add flag to events so user can indicate if they are attending
10) view to show which users are attending an event
11) view to show which posts have referenced the current event
12) update context with these new views for either all pages or just the event node page
13) only allow content admins to submit/publish event
14) authenticated users can view events
15) events are not added to the main menu or promoted by default, but published automatically with no preview
16) all events view is a link on the main menu

There's a lot of room for improvement aesthetically.

### CODE REVIEW

**Comment by janelletavares** [comment]
17) Added no results behavior to new hire views so that they consistently appear and there's always a way to navigate to the new hire archive.

**Comment by chris-hamper** [comment]
Problems:
- Authenticated users can see "New Event" menu link - not sure why this is happening

Some other suggestions:
- Change "Last event in series" to "Related events", change field's description, and allow Unlimited values - this field can be useful for more than just chaining together recurring events
- Make the "Registration URL" into a link, using the "Link" contrib module, maybe rename to "Registration Link"
- "Event Site" is ambiguous, change to "Event Link" and make it a Link
- Change "Company" in Venus field to something more general, like "Location Name" - It's not necessarily happening at a company
- Reorder fields in Event node form, it feels disjointed and confusing currently
- Make the address fields optional - there might be an Acquia-wide event or something that doesn't have a specific address.
- Instead of having a "no posts" message when no posts are related to event, just hide the related posts view - this just clutters the page
- Same for attendees - plus seeing nobody is attending an event yet has a discouraging effect
- Change "Click to indicate you are attending" to "I want to attend!", similar for un-attend
- In the future something like this should be treated as an Epic, and split into multiple pulls (as it was split into multiple JIRA issues), not all shoved into one big pull.  That will be easier to test, and less likely to break or give other problems during development.

I'm OK with merging this and making a JIRA issue for fixes/improvements

**Comment by chris-hamper** [comment]
Clearing the cache seemed to fix the menu item problem I had mentioned.

**Comment by janelletavares** [comment]
Thanks for the thorough review!  I'm going to respond to your bullet points
as if they were numbered.

1&6)  I can easily make these field changes before the merge.
2&3)  I was wondering if something like the link contrib module existed, I
just didn't get around to that detail.  I will make that change before the
merge.
4&5) Are these theming user stories?
7&8) Very fair, I will make these changes before the merge.
9) I chose the flag text so as to not confuse these with the registration
links.  There's room for improvement with what I've written, but I think
people will confuse "I want to attend!" with a link to the registration
form.  People understand Like/Unlike more readily than these flags.  Let's
discuss it more at the next meeting.
10) If there was more time, I would have done multiple pulls requests.

**Comment by chris-hamper** [comment]
4&5)  can be changed in the Events > Manage fields

**Comment by janelletavares** [comment]
For the events form, what would feel less disjointed and confusing?  I tried to order the fields in an engaging order for viewing the published event, and kept that order for the events form.

**Comment by janelletavares** [comment]
I also realized that the filters I had on the event views was wrong.  We are mostly concerned about events that haven't happened yet.  I made a view specifically for past events.  The events closest to now should appear at the top of any of these lists.

**Comment by chris-hamper** [comment]
Shouldn't the past events view be sorted descending to keep the events closest to today at the top?  It looks like the last commit broke the admin content view, too.  Reverting that commit fixed both.

Other than that, I fixed the order of the Sticky sorting to make sticky events rise to the top.

**Comment by chris-hamper** [comment]
Something in the feature got fubar-ed at some point, possibly my merge with master a couple days ago to resolve conflicts was bad.

I'm rebuilding the branch to get rid of that commit.

**Comment by chris-hamper** [comment]
Ok. I think things are good now. I removed the commit that sorted past events wrong, and added my commit to fix the sticky events sorting.

@janelletavares can you please test this on your local, if you still have all the events you were testing with there.  Because of the weirdness I did to fix this branch, you'll need to first wipe out the branch you have, and check out the new one, with:

    git branch -D events
    git fetch
    git checkout events

then do the usual drush feature revert process and test.  Let me know if it looks good, and merge it.

**Comment by janelletavares** [comment]
Thanks, Chris.  I'll take a look this morning.

**Comment by janelletavares** [comment]
Looks good.  I noticed one thing, that I'm sorting my posts about an event view by 'post date' instead of 'published at'.  Fixed.  I'm happy to merge anytime now.

**Comment by chris-hamper** [comment]
Looks good to me! Merging and pushing to Stage...

**Pull request merged**
