### PR TITLE
AU-573 improve media exp

### PR DESCRIPTION
**Pull request by chris-hamper**
- Adds and enables the Ember admin theme, which is used by several of Acquia's other internal sites, and is much more consistent with the front-end theme.  This also improves the appearance of the media browser, and makes the Images and Video fields on the New Post form more consistent.
- Fixes order of the fields on the node form so that the Images and Video fields are together.
- Removes the Tags field from the Drizzle Articles feature

### CODE REVIEW

**Comment by chris-hamper** [comment]
Fixed the messages and resolved merge conflicts.  I also fixed a minor bug with the "Featured Event" view that shows an event in the footer.  I removed the "None Found" message from the view, so the block simply doesn't show up in the footer when there is no featured event.

This should be ready for one more quick test and a merge.

**Comment by janelletavares** [comment]
That null result behavior makes sense.  I'll retest and merge.

**Comment by janelletavares** [comment]
@chris-hamper  When there's no featured event now, I see the whole footer go away.  I can't see any of the Acquia links in my local DB, so is this missing footer because the Acquia links need to be rebuilt?  Do you see this behavior, as well?  We may need to change the no results behavior to be a string of spaces or something like that to just keep the blocks around.

**Comment by janelletavares** [comment]
@chris-hamper Your merge appears to have removed the events blocks from the sidebars.  Don't know how that happened, but that's not desired.

**Comment by janelletavares** [comment]
It looks like you changed the no results behavior for all event views (All displays) instead of just the featured event view (this block override)  Fixing that and then will merge.

**Pull request merged**
